common:
  user_dir: ???
  #fp16: true

generation:
  beam: 20
  lenpen: 0.0
  max_len_a: 1.0
  max_len_b: 0
  lm_weight: 0

common_eval:
  results_path: ???
  path: ???

dataset:
  max_tokens: 1000
  gen_subset: test
  num_workers: 0

override:
  noise_prob: 0.0
  noise_snr: 0
  modalities: ['visual', 'audio']
  llm_ckpt_path: ???
  w2v_path: ???